### ISSUE TITLE
Log "Send Now" action as its own EventType in the EventLog

### ISSUE THREAD

**Issue by asinay** [psteiwer/PivotSubscriptions#69]
Hello,
It would be nice to log the "Send Now" action as its own EventType in the EventLog.  Currently, there is no way to tell the difference between a Send Now email and a scheduled one, so it might be confusing to see that it was send outside the subscription "window".

**Comment by psteiwer** [comment]
@asinay the current way to distinguish this is to look at the "username" column, if it was _SYSTEM, then you can assume that the task sent the subscription. If there is a different username, you can assume it was someone else.

That being said, I was considering adding a new event called "sendNow" instead of "sendSubscription"
